// uiohook-napi и nut-js используют разные системы кодов клавиш (разные нативные библиотеки).
// Записываем клавишу через uiohook (глобальный перехват — единственный способ поймать
// «нажми любую клавишу» в контексте ОС), а нажимаем её потом через nut-js (единственный,
// который умеет эмулировать нажатия). Эта таблица связывает имена клавиш между ними.

const { Key } = require("@nut-tree-fork/nut-js");
const { UiohookKey } = require("uiohook-napi");

const UIOHOOK_NAME_TO_NUTJS_KEY = {
  Backspace: Key.Backspace,
  Tab: Key.Tab,
  Enter: Key.Enter,
  CapsLock: Key.CapsLock,
  Escape: Key.Escape,
  Space: Key.Space,
  PageUp: Key.PageUp,
  PageDown: Key.PageDown,
  End: Key.End,
  Home: Key.Home,
  ArrowLeft: Key.Left,
  ArrowUp: Key.Up,
  ArrowRight: Key.Right,
  ArrowDown: Key.Down,
  Insert: Key.Insert,
  Delete: Key.Delete,
  0: Key.Num0,
  1: Key.Num1,
  2: Key.Num2,
  3: Key.Num3,
  4: Key.Num4,
  5: Key.Num5,
  6: Key.Num6,
  7: Key.Num7,
  8: Key.Num8,
  9: Key.Num9,
  A: Key.A,
  B: Key.B,
  C: Key.C,
  D: Key.D,
  E: Key.E,
  F: Key.F,
  G: Key.G,
  H: Key.H,
  I: Key.I,
  J: Key.J,
  K: Key.K,
  L: Key.L,
  M: Key.M,
  N: Key.N,
  O: Key.O,
  P: Key.P,
  Q: Key.Q,
  R: Key.R,
  S: Key.S,
  T: Key.T,
  U: Key.U,
  V: Key.V,
  W: Key.W,
  X: Key.X,
  Y: Key.Y,
  Z: Key.Z,
  Numpad0: Key.NumPad0,
  Numpad1: Key.NumPad1,
  Numpad2: Key.NumPad2,
  Numpad3: Key.NumPad3,
  Numpad4: Key.NumPad4,
  Numpad5: Key.NumPad5,
  Numpad6: Key.NumPad6,
  Numpad7: Key.NumPad7,
  Numpad8: Key.NumPad8,
  Numpad9: Key.NumPad9,
  NumpadMultiply: Key.Multiply,
  NumpadAdd: Key.Add,
  NumpadSubtract: Key.Subtract,
  NumpadDecimal: Key.Decimal,
  NumpadDivide: Key.Divide,
  NumpadEnter: Key.Enter,
  LeftShift: Key.LeftShift,
  RightShift: Key.RightShift,
  Ctrl: Key.LeftControl,
  CtrlRight: Key.RightControl,
  Alt: Key.LeftAlt,
  AltRight: Key.RightAlt,
  Meta: Key.LeftSuper,
  MetaRight: Key.RightSuper,
  F1: Key.F1,
  F2: Key.F2,
  F3: Key.F3,
  F4: Key.F4,
  F5: Key.F5,
  F6: Key.F6,
  F7: Key.F7,
  F8: Key.F8,
  F9: Key.F9,
  F10: Key.F10,
  F11: Key.F11,
  F12: Key.F12,
  F13: Key.F13,
  F14: Key.F14,
  F15: Key.F15,
  F16: Key.F16,
  F17: Key.F17,
  F18: Key.F18,
  F19: Key.F19,
  F20: Key.F20,
  F21: Key.F21,
  F22: Key.F22,
  F23: Key.F23,
  F24: Key.F24,
  Semicolon: Key.Semicolon,
  Equal: Key.Equal,
  Comma: Key.Comma,
  Minus: Key.Minus,
  Period: Key.Period,
  Slash: Key.Slash,
  Backquote: Key.Grave,
  LeftBracket: Key.LeftBracket,
  Backslash: Key.Backslash,
  RightBracket: Key.RightBracket,
  Quote: Key.Quote,
  NumLock: Key.NumLock,
  ScrollLock: Key.ScrollLock,
  PrintScreen: Key.Print,
};

const UIOHOOK_CODE_TO_NAME = {};
for (const [name, code] of Object.entries(UiohookKey)) {
  UIOHOOK_CODE_TO_NAME[code] = name;
}

function keycodeToName(keycode) {
  return UIOHOOK_CODE_TO_NAME[keycode] || null;
}

function resolveNutjsKey(keyToPress) {
  if (!keyToPress || !keyToPress.name) return Key.Space;
  return UIOHOOK_NAME_TO_NUTJS_KEY[keyToPress.name] ?? Key.Space;
}

// Сырые Win32 virtual-key коды — отдельная таблица от resolveNutjsKey() выше: та отдаёт значение
// enum'а nut-js (для обычного, не-турбо режима — жмёт клавишу через nut-js/libnut), а эта — код
// для SendInput напрямую (нативный турбо, см. native-clicker/). Цифры и латинские буквы совпадают
// с ASCII-кодами не случайно — так они заданы в самой WinAPI (VK_0..VK_9 = 0x30..0x39, VK_A..VK_Z =
// 0x41..0x5A), остальное — из headers Win32 (WinUser.h).
const UIOHOOK_NAME_TO_VK_CODE = {
  Backspace: 0x08,
  Tab: 0x09,
  Enter: 0x0d,
  NumpadEnter: 0x0d, // отдельного VK для numpad-Enter нет — то же, что обычный Enter
  CapsLock: 0x14,
  Escape: 0x1b,
  Space: 0x20,
  PageUp: 0x21,
  PageDown: 0x22,
  End: 0x23,
  Home: 0x24,
  ArrowLeft: 0x25,
  ArrowUp: 0x26,
  ArrowRight: 0x27,
  ArrowDown: 0x28,
  PrintScreen: 0x2c,
  Insert: 0x2d,
  Delete: 0x2e,
  0: 0x30,
  1: 0x31,
  2: 0x32,
  3: 0x33,
  4: 0x34,
  5: 0x35,
  6: 0x36,
  7: 0x37,
  8: 0x38,
  9: 0x39,
  A: 0x41,
  B: 0x42,
  C: 0x43,
  D: 0x44,
  E: 0x45,
  F: 0x46,
  G: 0x47,
  H: 0x48,
  I: 0x49,
  J: 0x4a,
  K: 0x4b,
  L: 0x4c,
  M: 0x4d,
  N: 0x4e,
  O: 0x4f,
  P: 0x50,
  Q: 0x51,
  R: 0x52,
  S: 0x53,
  T: 0x54,
  U: 0x55,
  V: 0x56,
  W: 0x57,
  X: 0x58,
  Y: 0x59,
  Z: 0x5a,
  Meta: 0x5b,
  MetaRight: 0x5c,
  Numpad0: 0x60,
  Numpad1: 0x61,
  Numpad2: 0x62,
  Numpad3: 0x63,
  Numpad4: 0x64,
  Numpad5: 0x65,
  Numpad6: 0x66,
  Numpad7: 0x67,
  Numpad8: 0x68,
  Numpad9: 0x69,
  NumpadMultiply: 0x6a,
  NumpadAdd: 0x6b,
  NumpadSubtract: 0x6d,
  NumpadDecimal: 0x6e,
  NumpadDivide: 0x6f,
  F1: 0x70,
  F2: 0x71,
  F3: 0x72,
  F4: 0x73,
  F5: 0x74,
  F6: 0x75,
  F7: 0x76,
  F8: 0x77,
  F9: 0x78,
  F10: 0x79,
  F11: 0x7a,
  F12: 0x7b,
  F13: 0x7c,
  F14: 0x7d,
  F15: 0x7e,
  F16: 0x7f,
  F17: 0x80,
  F18: 0x81,
  F19: 0x82,
  F20: 0x83,
  F21: 0x84,
  F22: 0x85,
  F23: 0x86,
  F24: 0x87,
  NumLock: 0x90,
  ScrollLock: 0x91,
  LeftShift: 0xa0,
  RightShift: 0xa1,
  Ctrl: 0xa2,
  CtrlRight: 0xa3,
  Alt: 0xa4,
  AltRight: 0xa5,
  Semicolon: 0xba,
  Equal: 0xbb,
  Comma: 0xbc,
  Minus: 0xbd,
  Period: 0xbe,
  Slash: 0xbf,
  Backquote: 0xc0,
  LeftBracket: 0xdb,
  Backslash: 0xdc,
  RightBracket: 0xdd,
  Quote: 0xde,
};

function resolveVkCode(keyToPress) {
  if (!keyToPress || !keyToPress.name) return 0x20; // Space
  return UIOHOOK_NAME_TO_VK_CODE[keyToPress.name] ?? 0x20;
}

module.exports = { keycodeToName, resolveNutjsKey, resolveVkCode };
