// uiohook-napi и nut-js используют разные системы кодов клавиш (разные нативные библиотеки).
// Записываем клавишу через uiohook (глобальный перехват — единственный способ поймать
// «нажми любую клавишу» в контексте ОС), а нажимаем её потом через nut-js (единственный,
// который умеет эмулировать нажатия). Эта таблица связывает имена клавиш между ними.

const { Key } = require("@nut-tree-fork/nut-js");
const { UiohookKey } = require("uiohook-napi");

const UIOHOOK_NAME_TO_NUTJS_KEY = {
  Backspace: Key.Backspace,
  Tab: Key.Tab,
  Enter: Key.Enter,
  CapsLock: Key.CapsLock,
  Escape: Key.Escape,
  Space: Key.Space,
  PageUp: Key.PageUp,
  PageDown: Key.PageDown,
  End: Key.End,
  Home: Key.Home,
  ArrowLeft: Key.Left,
  ArrowUp: Key.Up,
  ArrowRight: Key.Right,
  ArrowDown: Key.Down,
  Insert: Key.Insert,
  Delete: Key.Delete,
  0: Key.Num0,
  1: Key.Num1,
  2: Key.Num2,
  3: Key.Num3,
  4: Key.Num4,
  5: Key.Num5,
  6: Key.Num6,
  7: Key.Num7,
  8: Key.Num8,
  9: Key.Num9,
  A: Key.A,
  B: Key.B,
  C: Key.C,
  D: Key.D,
  E: Key.E,
  F: Key.F,
  G: Key.G,
  H: Key.H,
  I: Key.I,
  J: Key.J,
  K: Key.K,
  L: Key.L,
  M: Key.M,
  N: Key.N,
  O: Key.O,
  P: Key.P,
  Q: Key.Q,
  R: Key.R,
  S: Key.S,
  T: Key.T,
  U: Key.U,
  V: Key.V,
  W: Key.W,
  X: Key.X,
  Y: Key.Y,
  Z: Key.Z,
  Numpad0: Key.NumPad0,
  Numpad1: Key.NumPad1,
  Numpad2: Key.NumPad2,
  Numpad3: Key.NumPad3,
  Numpad4: Key.NumPad4,
  Numpad5: Key.NumPad5,
  Numpad6: Key.NumPad6,
  Numpad7: Key.NumPad7,
  Numpad8: Key.NumPad8,
  Numpad9: Key.NumPad9,
  NumpadMultiply: Key.Multiply,
  NumpadAdd: Key.Add,
  NumpadSubtract: Key.Subtract,
  NumpadDecimal: Key.Decimal,
  NumpadDivide: Key.Divide,
  NumpadEnter: Key.Enter,
  LeftShift: Key.LeftShift,
  RightShift: Key.RightShift,
  Ctrl: Key.LeftControl,
  CtrlRight: Key.RightControl,
  Alt: Key.LeftAlt,
  AltRight: Key.RightAlt,
  Meta: Key.LeftSuper,
  MetaRight: Key.RightSuper,
  F1: Key.F1,
  F2: Key.F2,
  F3: Key.F3,
  F4: Key.F4,
  F5: Key.F5,
  F6: Key.F6,
  F7: Key.F7,
  F8: Key.F8,
  F9: Key.F9,
  F10: Key.F10,
  F11: Key.F11,
  F12: Key.F12,
  F13: Key.F13,
  F14: Key.F14,
  F15: Key.F15,
  F16: Key.F16,
  F17: Key.F17,
  F18: Key.F18,
  F19: Key.F19,
  F20: Key.F20,
  F21: Key.F21,
  F22: Key.F22,
  F23: Key.F23,
  F24: Key.F24,
  Semicolon: Key.Semicolon,
  Equal: Key.Equal,
  Comma: Key.Comma,
  Minus: Key.Minus,
  Period: Key.Period,
  Slash: Key.Slash,
  Backquote: Key.Grave,
  LeftBracket: Key.LeftBracket,
  Backslash: Key.Backslash,
  RightBracket: Key.RightBracket,
  Quote: Key.Quote,
  NumLock: Key.NumLock,
  ScrollLock: Key.ScrollLock,
  PrintScreen: Key.Print,
};

const UIOHOOK_CODE_TO_NAME = {};
for (const [name, code] of Object.entries(UiohookKey)) {
  UIOHOOK_CODE_TO_NAME[code] = name;
}

function keycodeToName(keycode) {
  return UIOHOOK_CODE_TO_NAME[keycode] || null;
}

function resolveNutjsKey(keyToPress) {
  if (!keyToPress || !keyToPress.name) return Key.Space;
  return UIOHOOK_NAME_TO_NUTJS_KEY[keyToPress.name] ?? Key.Space;
}

module.exports = { keycodeToName, resolveNutjsKey };
