const { contextBridge, ipcRenderer, clipboard } = require("electron");

contextBridge.exposeInMainWorld("api", {
  getSettings: () => ipcRenderer.invoke("settings:get"),
  setSettings: (partial) => ipcRenderer.invoke("settings:set", partial),
  verifyLicense: (key) => ipcRenderer.invoke("license:verify", key),
  getMachineId: () => ipcRenderer.invoke("system:getMachineId"),
  pickActiveWindowTitle: () => ipcRenderer.invoke("system:pickActiveWindowTitle"),
  toggle: () => ipcRenderer.invoke("click:toggle"),
  getStatus: () => ipcRenderer.invoke("click:status"),
  pickPoint: () => ipcRenderer.invoke("point:pick"),
  pickPoints: () => ipcRenderer.invoke("points:pick"),
  sampleColor: (point) => ipcRenderer.invoke("color:sample", point),
  captureKey: () => ipcRenderer.invoke("key:capture"),
  openDonate: () => ipcRenderer.invoke("donate:open"),
  openExternal: (url) => ipcRenderer.invoke("system:openExternal", url),

  setSchedule: (hhmm, repeat, intervalMin) => ipcRenderer.invoke("schedule:set", hhmm, repeat, intervalMin),
  cancelSchedule: () => ipcRenderer.invoke("schedule:cancel"),

  startRecording: () => ipcRenderer.invoke("macro:startRecording"),
  stopRecording: () => ipcRenderer.invoke("macro:stopRecording"),
  saveMacro: (name, events, repeat, hotkey) => ipcRenderer.invoke("macro:save", name, events, repeat, hotkey),
  playMacro: (name) => ipcRenderer.invoke("macro:play", name),
  deleteMacro: (name) => ipcRenderer.invoke("macro:delete", name),
  updateMacro: (oldName, newName, repeat, hotkey) => ipcRenderer.invoke("macro:update", oldName, newName, repeat, hotkey),
  playMacroChain: (names) => ipcRenderer.invoke("macro:playChain", names),

  exportSettings: () => ipcRenderer.invoke("settings:export"),
  importSettings: () => ipcRenderer.invoke("settings:import"),

  listStartupApps: () => ipcRenderer.invoke("startup:list"),
  toggleStartupApp: (name, source, enable) => ipcRenderer.invoke("startup:toggle", name, source, enable),

  captureAndRecognizeText: () => ipcRenderer.invoke("ocr:capture"),
  copyText: (text) => clipboard.writeText(text),
  pickTextTriggerRegion: () => ipcRenderer.invoke("textTrigger:pickRegion"),
  pickImageTriggerTemplate: () => ipcRenderer.invoke("imageTrigger:pickTemplate"),

  pickClashRegion: () => ipcRenderer.invoke("clash:pickRegion"),
  getClashCards: () => ipcRenderer.invoke("clash:getCards"),
  getClashState: () => ipcRenderer.invoke("clash:getState"),
  startClashMatch: () => ipcRenderer.invoke("clash:startMatch"),
  startClashOvertime: () => ipcRenderer.invoke("clash:startOvertime"),
  resetClash: () => ipcRenderer.invoke("clash:reset"),
  recordClashManualPlay: (cardId) => ipcRenderer.invoke("clash:recordManualPlay", cardId),
  undoClashLastPlay: () => ipcRenderer.invoke("clash:undoLastPlay"),
  onClashState: (callback) => ipcRenderer.on("clash:state", (_e, state) => callback(state)),

  startRecordingScreen: () => ipcRenderer.invoke("record:start"),
  stopRecordingScreen: () => ipcRenderer.invoke("record:stop"),
  saveVideoRecording: (buffer) => ipcRenderer.invoke("record:saveVideo", buffer),
  openRecordingsFolder: () => ipcRenderer.invoke("record:openFolder"),
  listRecordMonitors: () => ipcRenderer.invoke("record:listMonitors"),
  showRecordHud: () => ipcRenderer.invoke("record:hudShow"),
  hideRecordHud: () => ipcRenderer.invoke("record:hudHide"),

  getUpdateInfo: () => ipcRenderer.invoke("update:get"),
  testTelegram: () => ipcRenderer.invoke("telegram:test"),
  getActivityLog: () => ipcRenderer.invoke("activity:get"),
  clearActivityLog: () => ipcRenderer.invoke("activity:clear"),

  getClipboardHistory: () => ipcRenderer.invoke("clipboard:getHistory"),
  clearClipboardHistory: () => ipcRenderer.invoke("clipboard:clear"),
  copyFromClipboardHistory: (text) => ipcRenderer.invoke("clipboard:copy", text),

  listNotes: () => ipcRenderer.invoke("notes:list"),
  createNote: () => ipcRenderer.invoke("notes:create"),
  showNote: (id) => ipcRenderer.invoke("notes:show", id),
  deleteNote: (id) => ipcRenderer.invoke("notes:delete", id),

  onStatus: (callback) => ipcRenderer.on("status:update", (_e, data) => callback(data)),
  onNote: (callback) => ipcRenderer.on("note:show", (_e, text) => callback(text)),
  onRecordingStopped: (callback) => ipcRenderer.on("recording:stopped", (_e, events) => callback(events)),
  onRecordingProgress: (callback) => ipcRenderer.on("recording:progress", (_e, count) => callback(count)),
  onActivityNew: (callback) => ipcRenderer.on("activity:new", (_e, entry) => callback(entry)),
  onUpdateAvailable: (callback) => ipcRenderer.on("update:available", (_e, info) => callback(info)),
  onClipboardNew: (callback) => ipcRenderer.on("clipboard:new", (_e, entry) => callback(entry)),
  onNotesChanged: (callback) => ipcRenderer.on("notes:changed", (_e, notes) => callback(notes)),
  onPanicStopRecording: (callback) => ipcRenderer.on("panic:stopRecording", () => callback()),
});
